src/Entity/Album.php
<?php

namespace App\Entity;

use App\Repository\AlbumRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AlbumRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Album
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dt_create;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank
     * @Assert\Length(
     *     min="3",
     *     max="100",
     *     minMessage="Минимальное количество символов в названии: 3",
     *     maxMessage="Максимальное количество символов в названии: 100"
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank
     * @Assert\Email(
     *     message = "'{{ value }}' - некорректный электронный адрес."
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * дата и время изменения альбома
     */
    private $dt_change;

    /**
     * @ORM\OneToMany(targetEntity=Photo::class, mappedBy="album", orphanRemoval=true)
     */
    private $photos;

    public function __construct()
    {
        $this->dt_create = new \DateTime();
        $this->photos = new ArrayCollection();
    }

    /**
     * @ORM\PreFlush()
     */
    public function saveDateOfChanges()
    {
        $this->dt_change = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDtCreate(): ?\DateTimeInterface
    {
        return $this->dt_create;
    }

    public function setDtCreate(\DateTimeInterface $dt_create): self
    {
        $this->dt_create = $dt_create;

        return $this;
    }

    public function getDtChange(): ?\DateTimeInterface
    {
        return $this->dt_change;
    }

    public function setDtChange(\DateTimeInterface $dt_change): self
    {
        $this->dt_change = $dt_change;

        return $this;
    }


    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Photo[]
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setAlbum($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->contains($photo)) {
            $this->photos->removeElement($photo);
            // set the owning side to null (unless already changed)
            if ($photo->getAlbum() === $this) {
                $photo->setAlbum(null);
            }
        }

        return $this;
    }
}

src/Entity/Photo.php
<?php

namespace App\Entity;

use App\Repository\PhotoRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PhotoRepository::class)
 */
class Photo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Album::class, inversedBy="photos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $album;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dt_create;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank
     * @Assert\Length(
     *     min="3",
     *     max="100",
     *     minMessage="Минимальное количество символов в названии: 3",
     *     maxMessage="Максимальное количество символов в названии: 100"
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_path;

    public function __construct()
    {
        $this->dt_create = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAlbum(): ?Album
    {
        return $this->album;
    }

    public function setAlbum(?Album $album): self
    {
        $this->album = $album;

        return $this;
    }

    public function getDtCreate(): ?\DateTimeInterface
    {
        return $this->dt_create;
    }

    public function setDtCreate(\DateTimeInterface $dt_create): self
    {
        $this->dt_create = $dt_create;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->image_path;
    }

    public function setImagePath(string $image_path): self
    {
        $this->image_path = $image_path;

        return $this;
    }


}

src/Form/Type/AlbumType.php
<?php


namespace App\Form\Type;


use App\Entity\Album;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AlbumType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextareaType::class, ['attr' => ['rows' => 2]])
            ->add('email', EmailType::class)
            ->add('save', SubmitType::class, ['label' => 'Сохранить'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Album::class,
        ]);
    }

}

src/Controller/AlbumsController.php
<?php


namespace App\Controller;



use App\Entity\Album;
use App\Entity\Photo;
use App\Form\Type\AlbumType;
use App\Form\Type\MyPhotoType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class AlbumsController extends AbstractController
{
    /**
     * @Route("/albums", name="albums_list")
     * @return Response
     */
    public function showAlbums()
    {
        $albums = $this->getDoctrine()
            ->getRepository(Album::class)
            ->findAll();
        return $this->render('albums.html.twig', [
            'title' => 'Список альбомов',
            'albums' => $albums,
        ]);
    }

    /**
     * @Route("/album/view/{id}", name="view_album")
     * @param int $id
     * @param Request $request
     * @return Response
     */

    public function viewAlbum(int $id, Request $request)
    {
        $album = $this->getDoctrine()
            ->getRepository(Album::class)
            ->find($id);

        if (!$album) {
            throw new NotFoundHttpException();
        }

        $photo = new Photo();
        $form = $this->createForm(MyPhotoType::class, $photo);

        $form->handleRequest($request);

        return $this->render('album/view.html.twig', [
            'title' => 'Просмотр альбома',
            'album' => $album,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/album/create", name="create_album")
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function createAlbum(Request $request)
    {
        $album = new Album();
        $form = $this->createForm(AlbumType::class, $album);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $album = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($album);
            $entityManager->flush();

            return $this->redirectToRoute('albums_list');
        }

        return $this->render('album/new_album.html.twig', [
            'form' => $form->createView(),
            'title' => 'Добавление альбома'
        ]);
    }

    /**
     * @Route("/album/change/{id}", name="change_album")
     * @param Request $request
     * @param int $id
     * @return RedirectResponse|Response
     */
    public function changeAlbum(Request $request, int $id)
    {
        $album = $this->getDoctrine()
            ->getRepository(Album::class)
            ->find($id);

        if (!$album) {
            throw new NotFoundHttpException();
        }

        $form = $this->createForm(AlbumType::class, $album);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $album = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($album);
            $entityManager->flush();

            return $this->redirectToRoute('albums_list');
        }

        return $this->render('album/change_album.html.twig', [
            'form' => $form->createView(),
            'title' => 'Изменение альбома',
            'id' => $id
        ]);
    }

    /**
     * @Route("/album/add_photo/{id}", name="add_photo")
     * @param Request $request
     * @param int $id id альбома
     * @return RedirectResponse|Response
     */
    public function addPhoto(Request $request, int $id)
    {
        $album = $this->getDoctrine()
            ->getRepository(Album::class)
            ->find($id);

        if (!$album) {
            throw new NotFoundHttpException();
        }

        $photo = new Photo();
        $form = $this->createForm(MyPhotoType::class, $photo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('file')->getData();

            $newFilename = uniqid().'.'.$imageFile->guessExtension();
            $directory = __DIR__ . '/../../public/assets/img';

            try {
                $imageFile->move(
                    $directory,
                    $newFilename
                );
            } catch (FileException $e) {
                throw new NotFoundHttpException();
            }

            $photo->setImagePath($newFilename);
            $photo->setAlbum($album);
            $photo = $form->getData();
            

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($photo);
            $entityManager->persist($album);
            $entityManager->flush();
        }

        $errors = $this->getErrorMessages($form);
        return new JsonResponse(['errors' => $errors]);

    }

    /**
     * @Route("/album/delete/{id}", name="delete_album")
     * @param int $id
     * @return Response
     */
    public function deleteAlbum(int $id)
    {
        $album = $this->getDoctrine()
            ->getRepository(Album::class)
            ->find($id);

        if (!$album) {
            throw new NotFoundHttpException();
        }
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($album);
        $entityManager->flush();

        return $this->redirectToRoute('albums_list');

    }

    /**
     * @Route("/photo/delete/{id}", name="delete_photo")
     * @param int $id
     * @return Response
     */
    public function deletePhoto(int $id)
    {
        $photo = $this->getDoctrine()
            ->getRepository(Photo::class)
            ->find($id);

        if (!$photo) {
            throw new NotFoundHttpException();
        }

        $album = $this->getDoctrine()
            ->getRepository(Album::class)
            ->find($photo->getAlbum()->getId());

        if (!$album) {
            throw new NotFoundHttpException();
        }

        $entityManager = $this->getDoctrine()->getManager();
        $album->removePhoto($photo);
        $entityManager->persist($album);
        $entityManager->flush();


        return $this->redirectToRoute('view_album', ['id' => $album->getId()]);

    }


    /**
     * @param FormInterface $form
     * @return array
     */
    protected function getErrorMessages(FormInterface $form): array
    {
        $errors = [];

        foreach ($form->getErrors() as $key => $error) {
            $errors[] = $error->getMessage();
        }
        //рекурсивный случай
        foreach ($form->all() as $child) {
            if (!$child->isValid()) {
                $errors[$child->getName()] = $this->getErrorMessages($child);
            }
        }

        return $errors;
    }

}

templates/album/change_album.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Изменение альбома:</h1>
    <form name="album" method="post" action="{{ url('change_album', {'id': id }) }}" novalidate>

        {{ form_row(form.title, {'label': 'Название альбома'}) }}

        {{ form_row(form.email, {'label': 'Электронная почта'}) }}

        {{ form_row(form.save, {'attr': {'class': 'button'}}) }}

    {{ form_end(form) }}
    <button class="button cancel"><a href="{{ url('albums_list') }}">Отмена</a></button>
{% endblock %}

templates/album/new_album.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Добавление нового альбома:</h1>
    <form name="album" method="post" novalidate>

        {{ form_row(form.title, {'label': 'Название альбома'}) }}

        {{ form_row(form.email, {'label': 'Электронная почта'}) }}

        {{ form_row(form.save, {'attr': {'class': 'button'}}) }}

    {{ form_end(form) }}
    <button class="button cancel"><a href="{{ url('albums_list') }}">Отмена</a></button>
{% endblock %}

templates/album/view.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <h1>"{{ album.title|capitalize  }}"</h1>
    <div id="app">
        <ul>
            {% for photo in album.photos %}
                <ul class="menu">
                    <li><img src="{{ asset('assets/img/' ~ photo.imagePath) }}" class="image--list"></li>
                    <li>{{ photo.title }}</li>
                    <li>Дата создания: {{ photo.dtCreate.format('Y-m-d') }}</li>
                    <li><a href="{{ url('delete_photo', {'id': photo.id}) }}">удалить фотографию</a></li>
                </ul>
            {% endfor %}
        </ul>
        <button class="button" @click="showForm">Добавить фото</button>

        <section class="add-photo-modal" id="add-photo-form" v-bind:style="formVision">
            <h1>Добавление фотографии в альбом "{{ album.title }}":</h1>
            <form name="my_photo" method="post" enctype="multipart/form-data" @submit="stopSubmit" novalidate>
                <div>
                    {{ form_label(form.file, 'Прикрепите файл') }}
                    {{ form_errors(form.file) }}
                    <ul class="errors">
                        <li>{% verbatim %}{{ errorFile }}{% endverbatim %}</li>
                    </ul>
                    {{ form_widget(form.file, { 'attr': {'ref': 'file', '@change': 'handleFileUpload'}}) }}
                </div>
                <div>
                    {{ form_label(form.title, 'Название фотографии') }}
                    {{ form_errors(form.title) }}
                    <ul class="errors">
                        <li>{% verbatim %}{{ errorTitle }}{% endverbatim %}</li>
                    </ul>
                    {{ form_widget(form.title, {'attr': {'v-model': 'title'}}) }}
                </div>
                {{ form_label(form.save) }}
                {{ form_widget(form.save, {'attr': {'class': 'button', '@click': 'submitFile'}}) }}

                {{ form_widget(form._token, {'attr': {'ref': 'token'}}) }}
                <input type="hidden" id="album_id" ref="albumId" value="{{ album.id }}" />

                {{ form_end(form) }}

            </form>
                <button class="button cancel" @click="hideForm">Отмена</button>
        </section>
        <div class="overlay" v-bind:style="formVision"></div>
    </div>
{% endblock %}